### ISSUE TITLE
inkids_rare.bed.gz test file available?

### ISSUE THREAD

**Issue by ChristopherWilks** [ryanlayer/giggle#10]
Hi Ryan,

Is it possible that you can make the file you tested Giggle and the other tools with, inkids_rare.bed.gz, available for replication purposes?  I understand that may not be possible if it's confidential, otherwise it'd be great to have it alongside the example RME data tests that you've already very helpfully provided and documented.

Thanks,
Chris

**Comment by ryanlayer** [comment]
Thanks for pointing this out.  As you guessed I cannot share that exact
set, but I will try and get something up there soon.

On Thu, Jun 16, 2016 at 2:33 PM, ChristopherWilks <notifications@github.com>
wrote:

> Hi Ryan,
>
> Is it possible that you can make the file you tested Giggle and the other
> tools with, inkids_rare.bed.gz, available for replication purposes? I
> understand that may not be possible if it's confidential, otherwise it'd be
> great to have it alongside the example RME data tests that you've already
> very helpfully provided and documented.
>
> Thanks,
> Chris
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ryanlayer/giggle/issues/10>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAlDUXsHierapYo6Cl6MKoKONy1XoRRkks5qMbMogaJpZM4I3yD8>
> .
>



-- 
Ryan Layer

**Comment by ChristopherWilks** [comment]
thanks, that would be useful.
