### ISSUE TITLE
examples for plotting utilities in scripts folder

### ISSUE THREAD

**Issue by avilella** [ryanlayer/giggle#20]
I successfully used the `giggle_heat_map.py` script for an example result against the RME dataset:

```
~/giggle/scripts/giggle_heat_map.py -i $query.result \
 -o $query.png \
-s ~/giggle/examples/rme/states.txt \
 -c ~/giggle/examples/rme/EDACC_NAME.txt
```

It would be great to have examples on how the other scripts can be used in the scripts folder. Thx

**Comment by ryanlayer** [comment]
In fact, there is complete documentation for every experiment and every figure in the paper. They are listed in the supplement and collected here: https://github.com/ryanlayer/giggle/tree/master/experiments
