### ISSUE TITLE
Availability of test data

### ISSUE THREAD

**Issue by retrogenomics** [ryanlayer/giggle#22]
I cannot access to the test dataset using this command line:
`wget https://s3.amazonaws.com/layerlab/giggle/roadmap/roadmap_sort.tar.gz`

I get the following error:

> --2017-07-05 11:41:05--  https://s3.amazonaws.com/layerlab/giggle/roadmap/roadmap_sort.tar.gz
> Resolving s3.amazonaws.com... 54.231.114.100
> Connecting to s3.amazonaws.com|54.231.114.100|:443... connected.
> HTTP request sent, awaiting response... 403 Forbidden
> 2017-07-05 11:41:06 ERROR 403: Forbidden.

Maybe it's an issue of access rights for the folder in which the dataset is stored?
Thanks
Gael

**Comment by ryanlayer** [comment]
Yep. The ACL was wrong. It should be fixed now.

**Comment by retrogenomics** [comment]
Thanks, indeed !
