### ISSUE TITLE
toolshed rename.py error

### ISSUE THREAD

**Issue by HGENETIC** [ryanlayer/giggle#23]
Hi,

I'm running through your readme file and compiling giggle, i have reached this part of the procedure:
mkdir split

pip install toolshed --user

python $GIGGLE_ROOT/examples/rme/rename.py \
    $GIGGLE_ROOT/examples/rme/states.txt \
    $GIGGLE_ROOT/examples/rme/EDACC_NAME.txt \
    "orig/*gz" \
    "split/"**

but keep getting this error about the syntax on line 35:

  File "/home/sejjhwi/GIGGLE/giggle/examples/rme/rename.py", line 35
    print fname
              ^
SyntaxError: Missing parentheses in call to 'print'**

do you kow how I can overcome this problem and continue with the installation?

Many thanks

Hywel

**Comment by brentp** [comment]
the script is for python 2 but you are using python 3. can you update your environment so that a python 2 install is used for `python`?

**Comment by HGENETIC** [comment]
Thanks for the explanation, I can use chose to use python 2 instead of 3 so will just recompile my environment and try again. It’s a great piece of software and I’m really excited to play with some of my data!

Cheers

Hywel
