### ISSUE TITLE
GIGGLE on Singularity

### ISSUE THREAD

**Issue by HugoGuillen** [ryanlayer/giggle#53]
Hi all,

Thanks for the excellent resource! I just made a wrapper for running GIGGLE on a Singularity container [https://github.com/HugoGuillen/giggle-singularity](https://github.com/HugoGuillen/giggle-singularity). Might it help other users if it's included in the list of APIs?

Best,
Hugo.

**Comment by ryanlayer** [comment]
For sure! Can you do a pull request on the README with the relevant info?

**Comment by HugoGuillen** [comment]
Done, thanks!
