### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by rysterzhu** [ryanlayer/giggle#69]
Ubuntu 22. gcc 11
gcc -O2 -D_FILE_OFFSET_BITS=64 -Werror -Wuninitialized -DBLOCK_STORE  -o ../bin/giggle giggle.c ../obj/bpt.o ../obj/disk_file_header.o ../obj/disk_store.o ../obj/zlib_wrapper.o ../obj/fastlz_wrapper.o ../obj/cache.o ../obj/data_reg.o ../obj/file_read.o ../obj/giggle_index.o ../obj/lists.o ../obj/ll.o ../obj/util.o ../obj/timer.o ../obj/wah.o ../obj/kfunc.o ../obj/index.o ../obj/offset_index.o ../obj/metadata_index.o../obj/query_filter.o ../obj/search.o ../obj/leaf.o ../obj/pq.o ../obj/jsw_avltree.o ../obj/fastlz.o \
	-I../lib/htslib \
	-DSAMTOOLS=1 \
	../lib/htslib/libhts.a \
	-ldl -lz -lm -pthread -lcurl -lcrypto
/usr/bin/ld: ../obj/bpt.o:(.data+0x0): multiple definition of `ORDER'; /tmp/ccQ7Y6Fk.o:(.bss+0x210): first defined here
/usr/bin/ld: ../obj/bpt.o:(.bss+0x1c0): multiple definition of `cache'; /tmp/ccQ7Y6Fk.o:(.bss+0x2c0): first defined here
/usr/bin/ld: ../obj/bpt.o:(.data.rel.local+0x0): multiple definition of `bpt_node_cache_handler'; /tmp/ccQ7Y6Fk.o:(.bss+0x1f0): first defined here
/usr/bin/ld: ../obj/bpt.o:(.bss+0x108): multiple definition of `bpt_node_repair'; /tmp/ccQ7Y6Fk.o:(.bss+0x1e8): first defined here
/usr/bin/ld: ../obj/bpt.o:(.bss+0x100): multiple definition of `append'; /tmp/ccQ7Y6Fk.o:(.bss+0x1e0): first defined here
/usr/bin/ld: ../obj/bpt.o:(.bss+0x0): multiple definition of `leaf_data_cache_handler'; /tmp/ccQ7Y6Fk.o:(.bss+0xd0): first defined here
/usr/bin/ld: ../obj/bpt.o:(.bss+0x20): multiple definition of `giggle_data_handler'; /tmp/ccQ7Y6Fk.o:(.bss+0x100): first defined here
/usr/bin/ld: ../obj/bpt.o:(.bss+0xa8): multiple definition of `CACHE_FILE_NAME_PREFIX'; /tmp/ccQ7Y6Fk.o:(.bss+0x188): first defined here
/usr/bin/ld: ../obj/bpt.o:(.bss+0xb0): multiple definition of `ROOT_IDS_FILE_NAME'; /tmp/ccQ7Y6Fk.o:(.bss+0x190): first defined here
/usr/bin/ld: ../obj/bpt.o:(.bss+0xb8): multiple definition of `FILE_INDEX_FILE_NAME'; /tmp/ccQ7Y6Fk.o:(.bss+0x198): first defined here
/usr/bin/ld: ../obj/bpt.o:(.bss+0xc0): multiple definition of `CHRM_INDEX_FILE_NAME'; /tmp/ccQ7Y6Fk.o:(.bss+0x1a0): first defined here
/usr/bin/ld: ../obj/bpt.o:(.bss+0xc8): multiple definition of `METADATA_INDEX_FILE_NAME'; /tmp/ccQ7Y6Fk.o:(.bss+0x1a8): first defined here
/usr/bin/ld: ../obj/bpt.o:(.bss+0xd0): multiple definition of `offset_data_append_data'; /tmp/ccQ7Y6Fk.o:(.bss+0x1b0): first defined here
/usr/bin/ld: ../obj/bpt.o:(.bss+0xd8): multiple definition of `offset_data_size'; /tmp/ccQ7Y6Fk.o:(.bss+0x1b8): first defined here
......

**Comment by mchowdh200** [comment]
I've had a lot of trouble compiling giggle (and its bundled version of htslib) with your version of gcc on newer ubuntu distributions.  To that end, I've created a basic singularity based solution that I think would solve your problem in #68

**Comment by mchowdh200** [comment]
I'm going to go ahead and close this issue.  Feel free to open back up if the singularity approach doesn't work.
